name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs every day at 02:30 UTC
  workflow-dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f3000194@ds.study.iitm.ac.in - Make a daily change
        run: |
          echo "Daily commit $(date)" >> daily-commit-log.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-commit-log.txt
          git commit -m "Daily commit from GitHub Actions at $(date)" || echo "No changes to commit"
          git push

